language: node_js

node_js:
  - "0.12"
  - "iojs-2"

branches:
  except:
    - gh-pages

script:
  - npm test --cover

after_script: "npm install coveralls@2 && cat ./build/coverage/lcov.info | coveralls"
